-- Insertion de données dans la table Matiere
INSERT INTO Matiere (nom_matiere, coefficient) VALUES
('Mathématiques', 3),              
('Physique', 2),                   
('Informatique Générale', 4),      
('Programmation', 5),              
('Bases de Données', 4),           
('Chimie', 2),                     
('Biologie', 2),                   
('Statistiques', 3),               
('Mathématiques Avancées', 4),     
('Physique Appliquée', 3),         
('Biologie Moléculaire', 3),      
('Anglais Général', 2),          
('Linguistique Anglaise', 3),    
('Philosophie Antique', 3),      
('Philosophie Moderne', 4),      
('Comptabilité', 3),             
('Gestion des Entreprises', 4),  
('Espagnol', 2),                 
('Allemand', 2),                 
('Histoire Médiévale', 3),       
('Histoire Contemporaine', 4);
